version: "3.9" # optional since v1.27.0
services:
  optimiser_service:
    build: ./optimiser_service
    ports:
      - "5000:5000"
    environment:
      SVC_MOCK_GRID_OPERATOR_HOST: "http://mock_grid_operator_service:5001"
      SVC_MARKET_HOST: "http://market_service:5002"
      SVC_BATTERY_HOST: "http://battery_service:5003"
      SVC_LOG_LOCATION: "./logs"
    volumes:
      - "./docker/optimiser/logs:/code/logs"
  mock_grid_operator_service:
    build: ./mock_grid_operator_service
    ports:
      - "5001:5001"
  market_service:
    build: ./market_service
    ports:
      - "5002:5002"
  battery_service:
    build: ./battery_service
    ports:
      - "5003:5003"
    depends_on:
      - dynamodb-local
    environment:
      AWS_ACCESS_KEY_ID: "DUMMYIDEXAMPLE"
      AWS_SECRET_ACCESS_KEY: "DUMMYEXAMPLEKEY"
      SVC_DYNAMODB_HOST: "http://dynamodb-local:8000"
  dynamodb-local:
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ./data"
    image: "amazon/dynamodb-local:1.17.0"
    container_name: dynamodb-local
    ports:
      - "8000:8000"
    volumes:
      - "./docker/dynamodb:/home/dynamodblocal/data"
    working_dir: /home/dynamodblocal
