version: "3.9" # optional since v1.27.0
services:
  optimiser_service:
    build: ./optimiser_service
    ports:
      - "5000:5000"
  mock_grid_operator_service:
    build: ./mock_grid_operator_service
    ports:
      - "5001:5001"
  market_service:
    build: ./market_service
    ports:
      - "5002:5002"
